import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
          
            <body id="main" className={inter.className}>
            <Navbar />
            
                <div id="boxCollection">
            <div className="flex" id="backgroundOne"></div>
            <div className="flex" id="backgroundTwo"></div>

            <div id="backgroundThree"></div>
            <div id="backgroundFour"></div>
            <div id="backgroundFive"></div>
            <div id="backgroundSix"></div>
        
           
            {children}
            <div id="backgroundDiffuser"></div>
                </div>
            </body>
        </html>
    );
}
